name: usl_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.3
  - pandas>=2.2
  - scikit-learn>=1.7
  - matplotlib>=3.10
  - seaborn>=0.12
  - jupyterlab>=4.0
  - nbconvert
  - ipykernel
  - pip
  - pip:
    - kagglehub[pandas-datasets]
